version: '3'

services:
  inspector:
    image: ghebby/request_inspector:latest
    restart: unless-stopped  
    environment:
      - TZ=Europe/Rome
      - PORT=9001
    ports:
      # host:container
      - 9099:9001