version: '3'

services:
  request_inspector:
    build: .
    container_name: request_inspector
    restart: unless-stopped
    ports:
      - 8189:8189  
    environment:
      - TZ=Europe/Rome
  
networks:
  default:
    external:
      name: ${DOCKER_VPN}