name: Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build for Linux
        run: |
          mkdir -p ./dist/linux/${{ github.ref_name }}
          GOOS=linux GOARCH=amd64 go build -o ./dist/linux/${{ github.ref_name }}/request_inspector .
          cp -r ./static ./dist/linux/${{ github.ref_name }}/static
          cp ./Makefile ./dist/linux/${{ github.ref_name }}/Makefile
          tar -czf ./dist/linux/request_inspector_${{ github.ref_name }}.tar.gz -C ./dist/linux/${{ github.ref_name }}/ .
          rm -rf ./dist/linux/${{ github.ref_name }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/linux/request_inspector_${{ github.ref_name }}.tar.gz
          asset_name: request_inspector_${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghebby/request_inspector:${{ github.ref_name }}
            ghebby/request_inspector:latest